### ISSUE TITLE
Request for Missing Files: merge_transform_average.py and intersect_zonalstats_par.py

### ISSUE THREAD

**Issue by kerrydu** [ClimateImpactLab/carleton_mortality_2022#13]
Hello,

I am currently working with the code provided in this repository and noticed that the following files are missing:

merge_transform_average.py
intersect_zonalstats_par.py

These files are crucial for the analysis described in the documentation. Could you please provide these files or any guidance on how to obtain them?

Thank you for your assistance!

**Comment by brews** [comment]
Hello @kerrydu. Sorry for the late reply. Thanks for posting this issue.

Those missing scripts are used for climate data aggregation and they are not included in this repository. There are more general resources helpful for this:

* The `xagg` Python package: https://xagg.readthedocs.io/en/latest/
* Tamma's `stagg` package for R: https://github.com/tcarleton/stagg (paper at https://doi.org/10.1016/j.envsoft.2024.106202)
* Also, this climate econmetric tutorial: https://climateestimate.net/content/getting-started.html

**Comment by kerrydu** [comment]
Many thanks for your reply @brews
